global:
  wait_after_load_seconds: 12
  animation_detection_threshold: 0.5
  viewport_width: 1920
  viewport_height: 1080
  device_scale_factor: 1.0
  storage_state: "auth/windy-state.json"

s3:
  bucket: "inno-virtual-trading"
  prefix: "windy-capture"

categories:
  - name: radar
    enabled: true
    url: "https://www.windy.com/-Weather-radar-radar?radar,42.792,-80.753,7"
    schedule_interval_minutes: 5
    animation_frames: 1
    animation_frame_interval_ms: 300

  - name: satellite
    enabled: true
    url: "https://www.windy.com/-Satellite-satellite?satellite,42.792,-80.753,7"
    schedule_interval_minutes: 5
    animation_frames: 1
    animation_frame_interval_ms: 300

  - name: wind
    enabled: true
#    url: "https://www.windy.com/?42.792,-80.753,7"
    url: "https://www.windy.com/?45.603,-80.939,5,i:pressure,p:wind"
    schedule_interval_minutes: 5
    animation_frames: 20
    animation_frame_interval_ms: 100
